# Generated by Django 4.2.5 on 2023-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdriveapi', '0002_alter_serviceticket_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='experience',
            field=models.CharField(max_length=25),
        ),
    ]
