# Generated by Django 4.2.5 on 2023-09-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdriveapi', '0004_alter_serviceticket_advisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='technician',
        ),
    ]
