# Generated by Django 4.2.5 on 2023-09-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdriveapi', '0005_remove_serviceticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to='sdriveapi.technician'),
        ),
    ]
