# Generated by Django 4.2.5 on 2023-09-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdriveapi', '0006_serviceticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='ro_identifier',
            field=models.IntegerField(default=0),
        ),
    ]
