# Generated by Django 4.2.5 on 2023-09-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdriveapi', '0007_serviceticket_ro_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='date_completed',
            field=models.DateField(default='2033-10-31'),
        ),
    ]
