# Generated by Django 4.2.5 on 2023-09-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdriveapi', '0008_alter_serviceticket_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
